name: Check Code Output

on:
  - push
  - pull_request

jobs:
  check-output:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests and Check Output
        run: |
          cd test
          python -m unittest testfile.py

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: 'true'

      - name: Run output check on changed Python files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *.py ]]; then
              echo "Checking $file..."
              python check_output.py "$file" || exit 1
            fi
          done
        shell: bash  
