name: Check Code Output

on:
  - push
  - pull_request

jobs:
  check-output:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests and Check Output
        run: |
          # Ensure you are in the correct directory with your test files
          cd test

          # Run all test files in the test directory, adjust if needed
          python -m unittest discover -s . -p "*.py"
