name: Check Code Output

on:
  - push
  - pull_request

jobs:
  check-output:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests and Check Output
        run: |
          # Run the tests in testfile.py using unittest
          OUTPUT=$(python3 -m unittest discover -s test -p "testfile.py")
          
          # Check if there was any output from the tests
          if [ -z "$OUTPUT" ]; then
            echo "No output detected! Failing the workflow."
            exit 1
          else
            echo "Output detected. Workflow passed."
          fi